-- MySQL Script generated by MySQL Workbench
-- Thu Feb  7 17:54:22 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema lab
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema lab
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `lab` DEFAULT CHARACTER SET utf8 ;
USE `lab` ;

-- -----------------------------------------------------
-- Table `lab`.`animal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lab`.`animal` (
  `id_animal` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `precio` DOUBLE NOT NULL,
  `raza` VARCHAR(20) NOT NULL,
  `estado` VARCHAR(10) NOT NULL,
  `promedio_lt` DOUBLE NOT NULL,
  `estado_venta` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`id_animal`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8
COMMENT = 'tabla animal para el proyecto, su clave primaria sera el id.';


-- -----------------------------------------------------
-- Table `lab`.`finca`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lab`.`finca` (
  `id_finca` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `hectareas` INT(11) NOT NULL,
  PRIMARY KEY (`id_finca`),
  INDEX `usuario_id_idx` (`id_finca` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `lab`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lab`.`usuario` (
  `id_usuario` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `contrasena` VARCHAR(45) NOT NULL,
  `correo` VARCHAR(45) NOT NULL,
  `telefono` VARCHAR(11) NOT NULL,
  `tipo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_usuario`),
  UNIQUE INDEX `nombre_UNIQUE` (`nombre` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
